backend_src/IAM/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='IAM'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:id>/',views.detail,name='event_detail'),
    path('<int:id>/speakers/',views.speakerlist,name='event_speakers'),
    path('<int:id>/speakers/<int:speaker_id>/',views.speakerDetail,name='event_speakerDetail'),
    path('<int:id>/tracks/',views.tracklist,name='event_tracks'),
    path('<int:id>/tracks/<int:track_id>/projects/',views.projectlist,name='project_list'),
    path('<int:id>/tracks/<int:track_id>/projects/<int:project_id>/',views.projectDetail,name='project_detail'),
    path('<int:id>/winners/tracks/',views.WinnerTracks,name='event_winnerstracks'),
    path('<int:id>/winners/tracks/<int:track_id>/',views.WinnersList,name='event_winnerslist'),
]

backend_src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home_page.urls')),
    path('recruiters/',include('recruiters.urls')),
    path('details/',include('why_us_and_procedure.urls')),
    path('course/',include('courses.urls')),
    path('IAM/',include('IAM.urls')),
    path('placements/',include('placements.urls')),
    path('team/',include('team.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend_src/IAM/models.py
from django.db import models

# Create your models here.
class Introduction(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return self.title

class IAM(models.Model):
    event_name = models.CharField(max_length=50)
    description = models.TextField()
    logo = models.FileField(upload_to='iam/logo', max_length=100,blank=True)
    date = models.DateField(auto_now=False, auto_now_add=False)
    winner_declared = models.BooleanField()
    def __str__(self):
        return self.event_name

class Speakers(models.Model):
    name = models.CharField(max_length=255)
    photo = models.FileField(upload_to='iam/speakers', max_length=100)
    designation = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    description = models.TextField()
    iam = models.ForeignKey("IAM.IAM", on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.name,self.iam.event_name)

class Tracks(models.Model):
    track = models.CharField(max_length=255)
    iam = models.ForeignKey("IAM.IAM", on_delete=models.CASCADE)
    def __str__(self):
        return "{} - {}".format(self.track,self.iam.event_name)

class Projects(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    track = models.ForeignKey("IAM.Tracks", on_delete=models.CASCADE,related_name='project_track')
    iam = models.ForeignKey("IAM.IAM", on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.name,self.iam.event_name)
    

class Participants(models.Model):
    name = models.CharField(max_length=255)
    iam = models.ForeignKey("IAM.IAM", on_delete=models.CASCADE)
    project = models.ForeignKey("IAM.Projects", on_delete=models.CASCADE,related_name='project_participants')

    def __str__(self):
        return "{} - {}".format(self.name,self.iam.event_name)
    
class Winners(models.Model):
    project = models.ForeignKey("IAM.Projects", on_delete=models.CASCADE,related_name='winners_project')
    iam = models.ForeignKey("IAM.IAM", on_delete=models.CASCADE)
    rank = models.IntegerField()

    def __str__(self):
        return "{}".format(self.project)
    

backend_src/IAM/views.py
from django.shortcuts import render
from .models import Introduction,IAM,Speakers,Projects, Tracks, Projects, Participants, Winners
# Create your views here.
def index(request):
    introduction = Introduction.objects.all()[0]
    events = IAM.objects.all().order_by('-date')
    context = {
        'introduction':introduction,
        'iam_events':events
    }
    return render(request,'IAM/index.html',context)

def detail(request,id):
    event = IAM.objects.get(pk=id)
    speakers = Speakers.objects.filter(iam=event).all()
    projects = Projects.objects.filter(iam=event).all()
    # print(len(speakers),len(projects))
    context = {
        'event':event,
        'speaker_len':len(speakers),
        'projects_len':len(projects),
        'winner_declared':event.winner_declared
    }
    return render(request,'IAM/detail.html',context)

def speakerlist(request,id):
    event = IAM.objects.get(pk=id)
    speakers = Speakers.objects.filter(iam=event).all()
    context = {
        'event_id':event.id,
        'speakers':speakers
    }
    return render(request,'IAM/speakerslist.html',context)

def speakerDetail(request,id,speaker_id):
    speaker = Speakers.objects.get(pk=speaker_id)
    # print(speaker.name)
    context = {
        'speaker':speaker
    }
    return render(request,'IAM/speakerDetail.html',context)

def tracklist(request,id):
    event = IAM.objects.get(pk=id)
    tracks = Tracks.objects.filter(iam=event).all()
    context = {
        'event_id':event.id,
        'tracks':tracks
    }
    return render(request,'IAM/tracks.html',context)

def projectlist(request,id,track_id):
    # event = IAM.objects.get(pk=id)
    track = Tracks.objects.get(pk=track_id)
    projects = Projects.objects.filter(track=track).all()
    context = {
        'event_id':id,
        'track_id':track_id,
        'track_name':track.track,
        'projects':projects
    }
    return render(request,'IAM/projectlist.html',context)

def projectDetail(request,id,track_id,project_id):
    project = Projects.objects.get(pk=project_id)
    context = {
        'project':project
    }
    return render(request,'IAM/projectDetail.html',context)

def WinnerTracks(request,id):
    event = IAM.objects.get(pk=id)
    tracks = Tracks.objects.filter(iam=event).all()
    context = {
        'event_id':event.id,
        'tracks':tracks
    }
    return render(request,'IAM/Winnerstracks.html',context)

def WinnersList(request,id,track_id):
    # event = IAM.objects.get(pk=id)
    track = Tracks.objects.get(pk=track_id)
    winners = Winners.objects.filter(project__track=track).order_by('rank')
    context = {
        'event_id':id,
        'track_id':track_id,
        'track_name':track.track,
        'winners':winners
    }
    return render(request,'IAM/winnerslist.html',context)

backend_src/templates/IAM/Winnerstracks.html
{% extends 'base/base_template.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'IAM/main.css' %} ">
<center>
    <h1 class='title'>Winners</h1>
    <hr>
</center>

<div class="row">
    <div class="content-block col-lg-10 col-md-10 col-sm-12 col-xs-12">

            <div class="row">
                <center>
                    {% for track in tracks %}
                        <a href="{% url 'IAM:event_winnerslist' id=event_id track_id=track.id %}">
                            <div class="content links-block col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                <span class="tile-text">{{track.track}}</span>
                            </div>
                        </a>
                    {% endfor %}
                </center>
            </div>
    </div>
</div>
{% endblock content %}

backend_src/templates/IAM/detail.html
{% extends 'base/base_template.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'IAM/main.css' %} ">
<center>
    <h1 class='title'>{{event.event_name}}</h1>
    <hr>
</center>
<p class='about_content'>
{{event.description}}
</p>
<div class="row">
    <div class="content-block col-lg-10 col-md-10 col-sm-12 col-xs-12">

            <div class="row">
                <center>
                    <a href="{% url 'IAM:event_speakers' event.id %}">
                        <div class="content links-block col-lg-4 col-md-4 col-sm-6 col-xs-12">
                            <span class="tile-text">Speakers</span> ({{speaker_len}})
                        </div>
                    </a>

                    <a href="{% url 'IAM:event_tracks' event.id %}">
                    <div class="content links-block col-lg-4 col-md-4 col-sm-6 col-xs-12">
                        <span class="tile-text">Projects</span> ({{projects_len}})
                    </div>
                    </a>

                    {% if winner_declared %}
                    <a href="{% url 'IAM:event_winnerstracks' event.id %}">
                    {% endif %}
                        <div class="content links-block col-lg-4 col-md-4 col-sm-6 col-xs-12">
                            <span class="tile-text">Winners</span> {% if winner_declared %}(declared) {% else %}(Not Declared){% endif %}
                        </div>
                    {% if winner_declared %}
                    </a>
                    {% endif %}

                </center>
            </div>
    </div>
</div>
{% endblock content %}

backend_src/templates/IAM/index.html
{% extends 'base/base_template.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'IAM/main.css' %} ">
<center>
    <h1 class='title'>{{introduction.title}}</h1>
    <hr>
</center>
<p class='about_content'>
{{introduction.content}}
</p>
<div class="row">
    <div class="content-block col-lg-10 col-md-10 col-sm-12 col-xs-12">
        {% for iam in iam_events %}
        <a href="{% url 'IAM:event_detail' iam.id %}">
            <div class="row content">
                <div class="event_logo col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <center>
                        <img class='thumbnail' src="{{iam.logo.url}}" alt="">
                    </center>
                </div>

                <div style="height: 100%;" class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                    <div style="height: 100%;" class="row">

                        <div style="height: 50%;" class="event_name col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <center>
                                <p class="">{{iam.event_name}}</p>
                            </center>
                        </div>
                        <hr>
                        <div style="height: 50%;" class="event_date col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <center>
                                <p class="">{{iam.date}}</p>
                            </center>
                        </div>
                    </div>
                </div>

            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock content %}

backend_src/templates/IAM/projectDetail.html
{% extends 'base/base_template.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'IAM/main.css' %} ">
<link rel="stylesheet" href="{% static 'IAM/speakerlist.css' %} ">
<style>
.team_members>span{
    text-decoration: none;
    list-style-type: none;
    font-size: 20px;
}
.project_description{
    text-align: justify;
}
</style>
<center>
    <h1 class='title'>{{project.name}}</h1>
    <hr>
</center>
<div class="row">
    <div class="content-block col-lg-10 col-md-10 col-sm-12 col-xs-12">
        <div class="content">
            <center>
            <h5><b>Team Members</b></h5>
            <div class="team_members">
                {% for participant in project.project_participants.all  %}
                    <span class="participants_name" >{{participant.name}}</span> {% if forloop.last %}{% else %},{% endif %}
                {% endfor %}
            </div>
            </center>
            <hr>
            <center><h5><b>Project Description</b></h5></center>
            <div class="project_description">
                <p style="font-size: 20px;">{{project.description}}</p>
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}

backend_src/templates/IAM/projectlist.html
{% extends 'base/base_template.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'IAM/main.css' %} ">
<link rel="stylesheet" href="{% static 'IAM/project_list.css' %} ">
<center>
    <h1 class='title'>Projects</h1>
    <hr>
    <h4>{{track_name}}</h4>
</center>
<br>
<br>
<div class="row">
    <div class="content-block col-lg-10 col-md-10 col-sm-12 col-xs-12">
        {% for project in projects %}
        <a href="{% url 'IAM:project_detail' id=event_id track_id=track_id project_id=project.id %}">
            <div class="row content">
                <div style="height: 100%;" class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
                    <div class="row">

                        <div style= class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <center>
                                <p class="project_title"><b>Title: </b>{{project.name}}</p>
                            </center>
                        </div>
                        <hr>
                        <center>
                        <h4><b>Team</b></h4>
                        <div class="row center-block">
                        {% for participant in project.project_participants.all  %}
                            <span class="participants_name" >{{participant.name}}</span> {% if forloop.last %} {% else %},{% endif %}
                        {% endfor %}
                        </div>
                        </center>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock content %}

backend_src/templates/IAM/speakerDetail.html
{% extends 'base/base_template.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'IAM/main.css' %} ">
<link rel="stylesheet" href="{% static 'IAM/speakerlist.css' %} ">
<center>
    <h1 class='title'>{{speaker.name}}</h1>
    <hr>
</center>
<div class="row">
    <div class="content-block col-lg-10 col-md-10 col-sm-12 col-xs-12">
        <div class="content">
            <center>
                <img style="height:300px;" src="{{speaker.photo.url}}" alt="">
                <h1><b>Designation:</b> {{speaker.designation}}</h1>
                <h1><b>Company:</b> {{speaker.company}}</h1>
            </center>
            <hr>
            <div class="">
                <p style="font-size: 20px;">{{speaker.description}}</p>
            </div>
        </div>
        
    </div>
</div>
{% endblock content %}

backend_src/templates/IAM/speakerslist.html
{% extends 'base/base_template.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'IAM/main.css' %} ">
<link rel="stylesheet" href="{% static 'IAM/speakerlist.css' %} ">
<center>
    <h1 class='title'>Speakers</h1>
    <hr>
</center>
<div class="row">
    <div class="content-block col-lg-10 col-md-10 col-sm-12 col-xs-12">
        <div class="row">
        {% for speaker in speakers %}
        <a href="{% url 'IAM:event_speakerDetail' id=event_id speaker_id=speaker.id %}">
            <div class="col-lg-3 col-sm-6">
                <div class="card hovercard">
                    <div class="cardheader">
                        <img class ="profile_pic" src="{{speaker.photo.url}}" alt="">
                    </div>
                    
                    <div class="info">
                        <div class="title">
                            {{speaker.name}}
                        </div>
                        <div class="desc">{{speaker.designation}}</div>
                        <div class="desc">{{speaker.company}}</div>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

backend_src/templates/IAM/tracks.html
{% extends 'base/base_template.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'IAM/main.css' %} ">
<center>
    <h1 class='title'>Project Tracks</h1>
    <hr>
</center>

<div class="row">
    <div class="content-block col-lg-10 col-md-10 col-sm-12 col-xs-12">

            <div class="row">
                <center>
                {% for track in tracks %}
                    <a href="{% url 'IAM:project_list' id=event_id track_id=track.id %}">
                        <div class="content links-block col-lg-4 col-md-4 col-sm-6 col-xs-12">
                            <span class="tile-text">{{track.track}}</span> ({{track.project_track.all|length}})
                        </div>
                    </a>
                {% endfor %}
                
                </center>
            </div>
    </div>
</div>
{% endblock content %}

backend_src/templates/IAM/winnerslist.html
{% extends 'base/base_template.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'IAM/main.css' %} ">
<link rel="stylesheet" href="{% static 'IAM/project_list.css' %} ">
<center>
    <h1 class='title'>Winning Projects</h1>
    <hr>
    <h4>{{track_name}}</h4>
</center>
<br>
<br>
<div class="row">
    <div class="content-block col-lg-10 col-md-10 col-sm-12 col-xs-12">
        {% for winner in winners %}
        <a href="{% url 'IAM:project_detail' id=event_id track_id=track_id project_id=winner.project.id %}">
            <div class="row content">
                <div style="height: 100%;" class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
                    <div class="row">

                        <div style= class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <center>
                                <p class="project_title"><b>Title: </b>{{winner.project.name}}</p>
                            </center>
                        </div>
                        <hr>
                        <center>
                        <h2><b>Position:</b> {{winner.rank}}</h2>
                        <h4><b>Team</b></h4>
                        <div class="row center-block">
                        {% for participant in winner.project.project_participants.all  %}
                            <span class="participants_name" >{{participant.name}}</span> {% if forloop.last %} {% else %},{% endif %}
                        {% endfor %}
                        </div>
                        </center>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock content %}